from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BundleSpec:
    filename: str
    title: str
    purpose: str
    sources: tuple[str, ...]


BUNDLE_SPECS = (
    BundleSpec(
        filename="knowledge-core.md",
        title="Core Workflow",
        purpose="Product Lock, role handling, run modes, QA, and bounded repair.",
        sources=(
            "core/product-lock.md",
            "core/workflow-protocol.md",
            "core/strict-match.md",
            "core/safe-run.md",
            "core/fast-run.md",
            "core/quality-check.md",
            "core/repair-loop.md",
        ),
    ),
    BundleSpec(
        filename="knowledge-products.md",
        title="Product Modules",
        purpose="Category-specific detection, invariants, risks, and QA.",
        sources=(
            "products/garments.md",
            "products/fabric.md",
            "products/earrings.md",
            "products/bracelets.md",
            "products/reflective-accessories.md",
        ),
    ),
    BundleSpec(
        filename="knowledge-styles.md",
        title="Style Cards",
        purpose="Reusable background, surface, lighting, and exclusion treatments.",
        sources=(
            "styles/sage-minimal-flatlay.md",
            "styles/clean-white-studio.md",
            "styles/warm-beige-editorial.md",
            "styles/dark-luxury-jewelry.md",
        ),
    ),
    BundleSpec(
        filename="knowledge-outputs.md",
        title="Output Profiles",
        purpose="Ecommerce and social composition and release constraints.",
        sources=(
            "outputs/ecommerce.md",
            "outputs/social.md",
        ),
    ),
)


def render_bundle(root: Path, spec: BundleSpec) -> str:
    source_list = "\n".join(f"- `{source}`" for source in spec.sources)
    sections: list[str] = []
    for source in spec.sources:
        source_path = root / source
        content = source_path.read_text(encoding="utf-8").strip()
        sections.append(
            f"<!-- BEGIN SOURCE: {source} -->\n\n"
            f"## Source: `{source}`\n\n"
            f"{content}\n\n"
            f"<!-- END SOURCE: {source} -->"
        )

    body = "\n\n---\n\n".join(sections)
    return (
        f"# Product Photo AI Workflows — {spec.title}\n\n"
        "> Generated by `tools/build_bundles.py` from canonical repository sources. "
        "Do not edit this bundle directly.\n\n"
        f"**Purpose:** {spec.purpose}\n\n"
        "## Included sources\n\n"
        f"{source_list}\n\n"
        "---\n\n"
        f"{body}\n"
    )


def expected_bundles(root: Path) -> dict[Path, str]:
    bundle_dir = root / "bundles"
    return {
        bundle_dir / spec.filename: render_bundle(root, spec)
        for spec in BUNDLE_SPECS
    }


def write_bundles(root: Path) -> None:
    for path, content in expected_bundles(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(root)}")


def check_bundles(root: Path) -> int:
    stale: list[Path] = []
    for path, expected in expected_bundles(root).items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(root))

    if stale:
        for path in stale:
            print(f"Outdated or missing bundle: {path}")
        print("Run: python tools/build_bundles.py")
        return 1

    print("Knowledge bundles are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build committed Knowledge bundles.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when committed bundles differ from canonical sources.",
    )
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]

    if args.check:
        return check_bundles(root)
    write_bundles(root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
